steps:
  - name: Attach date to filename
    id: attach-date
    args:
      - bash
      - -c
      - |
        # Get today's date
        current_date=$(date +%d-%m-%y)

        # Create new filename with date attached
        new_filename="cleaned_data_2k_lines_${current_date}.csv"
        echo "New filename: $new_filename"

  - name: Copy file to GCS
    id: copy-to-gcs
    args:
      - gsutil
      - cp
      - "datasets/cleaned_data_2k_lines.csv"
      - "gs://output_buc1/$new_filename"

      # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      #   args:
      #     - gsutil
      #     - cp
      #     - datasets/cleaned_data_2k_lines.csv
      #     - gs://output_buc1

      # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      #   args:
      #     - gcloud
      #     - functions
      #     - call
      #     - mlops-function
      #     - --region
      #     - us-central1
      #     - --data
      - "{}"
options:
  logging: CLOUD_LOGGING_ONLY
